### ISSUE TITLE
Avances alcanzados con la lectura y la placa de desarrollo (27-07-2017).

### ISSUE THREAD

**Issue by maxiyommi** [maxiyommi/primeros-pasos-BBB#1]
Hola @fchungo, abro este issues para ver tus avances y ademas acostumbrarnos a usar la plataforma GIT. Contame que hiciste esta semana.

- Avances en la lectura?
- Avances en los códigos?
- Dificultades?

Saludos,

**Comment by fchungo** [comment]
Hola @maxiyommi , te comento los avances hechos con la placa hasta ahora:
 
1. Códigos en node.js: Servidor Web y control de LED.
2. Comunicación con la placa a través de Cloud9.
3. Códigos en el bash de Linux: control de LED.
4. Códigos en C: uso de operadores y punteros, ingreso de variables tipo string, control de LED.
5. Códigos en C++: ingreso de variables tipo string, control de LED, control de LED usando POO.

Con respecto a los LEDs, lo que se hizo fue un programa que permita encender, apagar o 'flashear' los LEDs propios de la placa en todos los casos.
Con la lectura alcancé el final del capitulo 5, me falta el último título con su correspondiente ejemplo de código.
Comenté todos los códigos con detalle como para sean claros todos los pasos.
El avance fue sin dificultades ni obstáculos siempre usando como referencia el libro Exploring BBB.

Saludos.

**Comment by maxiyommi** [comment]
Genial @fchungo, podrías subir los códigos en una carpeta "CÓDIGOS", separada por lenguaje, a este repositorio.

Saludos,
